---
- hosts: all
  become: yes
  tasks:
  - name: Add service accounts
    user: 
      name: "{{ item }}"
      comment: service account
      create_home: no
      shell: /usr/bin/nologin
      state: present
    loop:
    - testuser1
    - testuser2
